"""Constants for MeteoAM component."""

from homeassistant.components.weather import (
    ATTR_CONDITION_CLEAR_NIGHT,
    ATTR_CONDITION_CLOUDY,
    ATTR_CONDITION_EXCEPTIONAL,
    ATTR_CONDITION_FOG,
    ATTR_CONDITION_LIGHTNING_RAINY,
    ATTR_CONDITION_PARTLYCLOUDY,
    ATTR_CONDITION_POURING,
    ATTR_CONDITION_RAINY,
    ATTR_CONDITION_SNOWY,
    ATTR_CONDITION_SNOWY_RAINY,
    ATTR_CONDITION_SUNNY,
    ATTR_CONDITION_WINDY,
    ATTR_FORECAST_CONDITION,
    ATTR_FORECAST_HUMIDITY,
    ATTR_FORECAST_NATIVE_TEMP,
    ATTR_FORECAST_NATIVE_TEMP_LOW,
    ATTR_FORECAST_NATIVE_WIND_SPEED,
    ATTR_FORECAST_PRECIPITATION_PROBABILITY,
    ATTR_FORECAST_TIME,
    ATTR_FORECAST_WIND_BEARING,
    ATTR_WEATHER_HUMIDITY,
    ATTR_WEATHER_PRESSURE,
    ATTR_WEATHER_TEMPERATURE,
    ATTR_WEATHER_WIND_BEARING,
    ATTR_WEATHER_WIND_SPEED,
)

DOMAIN = "meteoam"

HOME_LOCATION_NAME = "Home"

CONF_TRACK_HOME = "track_home"

DEFAULT_HOME_LATITUDE = 41.9027835
DEFAULT_HOME_LONGITUDE = 12.4963655

CONDITIONS_MAP = {
    ATTR_CONDITION_SUNNY: {"01", "02"},
    ATTR_CONDITION_PARTLYCLOUDY: {"04", "05", "34", "35"},
    ATTR_CONDITION_CLEAR_NIGHT: {"31"},
    ATTR_CONDITION_CLOUDY: {"06", "07", "36"},
    ATTR_CONDITION_FOG: {"03", "13", "14", "32", "33"},
    ATTR_CONDITION_RAINY: {"08"},
    ATTR_CONDITION_POURING: {"09", "15"},
    ATTR_CONDITION_LIGHTNING_RAINY: {"10"},
    ATTR_CONDITION_SNOWY_RAINY: {"11", "12"},
    ATTR_CONDITION_SNOWY: {"16"},
    ATTR_CONDITION_EXCEPTIONAL: {"17", "19"},  # storm, sand storm
    ATTR_CONDITION_WINDY: {"18"},
}

FORECAST_MAP = {
    ATTR_FORECAST_CONDITION: "icon",
    ATTR_FORECAST_PRECIPITATION_PROBABILITY: "tpp",
    ATTR_FORECAST_NATIVE_TEMP: "2t",
    ATTR_FORECAST_NATIVE_TEMP_LOW: "2t_min",
    ATTR_FORECAST_TIME: "localDateTime",
    ATTR_FORECAST_WIND_BEARING: "wdir",
    ATTR_FORECAST_NATIVE_WIND_SPEED: "wkmh",
    ATTR_FORECAST_HUMIDITY: "r",
}

ATTR_MAP = {
    ATTR_WEATHER_HUMIDITY: "r",
    ATTR_WEATHER_PRESSURE: "pmsl",
    ATTR_WEATHER_TEMPERATURE: "2t",
    ATTR_WEATHER_WIND_BEARING: "wdir",
    ATTR_WEATHER_WIND_SPEED: "wkmh",
}

# Reverse lookup: icon code -> HA condition (built once at import time)
CONDITION_LOOKUP: dict[str, str] = {
    code: condition for condition, codes in CONDITIONS_MAP.items() for code in codes
}
